## Data Hadis

In [303]:
import pandas as pd

pd.reset_option("^display")

##### Web scraping

In [304]:
df_scraper = pd.read_csv("scraper.csv")
df_scraper = df_scraper.sort_values("Nomor").reset_index().drop('index', axis=1)
df_scraper

,Nomor,Kitab,Bab,indo
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala..."
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur..."
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...
...,...,...,...,...
6981,7004,Tauhid,Firman Allah Ta\'ala: Dan Allah yang mencipata...,'Aku mendengar Nabi shallallahu 'alaihi wasall...
6982,7005,Tauhid,"Bacaan orang yang fajir dan munafik, serta sua...",'Perumpamaan orang mukmin yang membaca Al Qur'...
6983,7006,Tauhid,"Bacaan orang yang fajir dan munafik, serta sua...",'Beberapa orang bertanya Nabi shallallahu 'ala...
6984,7007,Tauhid,"Bacaan orang yang fajir dan munafik, serta sua...","'Akan muncul beberapa orang dari arah timur, m..."
6985,7008,Tauhid,Firman Allah Ta\'ala: dan kami letakkan neraca...,'Nabi shallallahu 'alaihi wasallam bersabda: '...

In [305]:
df_scraper['indo'] = df_scraper['indo'].str.replace("; \"",": \"")
df_scraper['Matan'] = [x.split(": \"",1)[-1] for x in df_scraper.indo]
df_scraper.head()

,Nomor,Kitab,Bab,indo,Matan
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala..."
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur..."
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...

#### bukhari.json

In [306]:
df_bukhari = pd.read_json("bukhari.json")
df_bukhari = df_bukhari.sort_values("haditsId").reset_index().drop('index', axis=1)
df_bukhari.head()

,imam,kitabId,babId,haditsId,arab,indo,sanads,related
0,bukhari,1,1,1,حَدَّثَنَا الْحُمَيْدِيُّ عَبْدُ اللَّهِ بْنُ ...,Telah menceritakan kepada kami [Al Humaidi Abd...,"[{'sanad': ['4698', '3443', '8272', '6796', '5...","[{'imam': 'bukhari', 'haditsId': '52'}, {'imam..."
1,bukhari,1,1,2,حَدَّثَنَا عَبْدُ اللَّهِ بْنُ يُوسُفَ قَالَ أ...,Telah menceritakan kepada kami [Abdullah bin Y...,"[{'sanad': ['5175', '6659', '8055', '5594', '4...","[{'imam': 'bukhari', 'haditsId': '2976'}, {'im..."
2,bukhari,1,1,3,حَدَّثَنَا يَحْيَى بْنُ بُكَيْرٍ قَالَ حَدَّثَ...,Telah menceritakan kepada kami [Yahya bin Buka...,"[{'sanad': ['8297', '6641', '5688', '7272', '5...","[{'imam': 'bukhari', 'haditsId': '4572'}, {'im..."
3,bukhari,1,1,4,حَدَّثَنَا مُوسَى بْنُ إِسْمَاعِيلَ قَالَ حَدّ...,Telah menceritakan kepada kami [Musa bin Isma'...,"[{'sanad': ['7721', '8153', '7710', '3307', '4...","[{'imam': 'bukhari', 'haditsId': '6970'}, {'im..."
4,bukhari,1,1,5,حَدَّثَنَا عَبْدَانُ قَالَ أَخْبَرَنَا عَبْدُ ...,Telah menceritakan kepada kami [Abdan] dia ber...,"[{'sanad': ['4943', '4716', '8621', '7272', '5...","[{'imam': 'bukhari', 'haditsId': '1769'}, {'im..."

## Preproccess

In [307]:
# df_praproses = df_bukhari
df_praproses = df_scraper

# df_praproses['Matan'] = [x.split(": \"",1)[-1] for x in df_praproses.indo]

df_praproses['Praproses'] = df_praproses['indo']
# df_praproses['Praproses'] = df_praproses['Matan']

#### Remove punctuation

In [308]:
import string
df_praproses['Praproses'] = df_praproses['Praproses'].str.replace('[{}]'.format(string.punctuation), '', regex=True)
# df_praproses['Praproses'] = df_praproses['Matan'].str.replace('[{}]'.format(string.punctuation), '', regex=True)
df_praproses.head()

,Nomor,Kitab,Bab,indo,Matan,Praproses
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",Semua perbuatan tergantung niatnya dan balasan...
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",Wahai Rasulullah bagaimana caranya wahyu turun...
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,Permulaaan wahyu yang datang kepada Rasulullah...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,Berkata Ibnu Abbas Rasulullah shallallahu ala...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu alaihi wasallam adalah ...

#### Case folding

In [309]:
df_praproses['Praproses'] = df_praproses['Praproses'].str.lower()
df_praproses.head()

,Nomor,Kitab,Bab,indo,Matan,Praproses
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",semua perbuatan tergantung niatnya dan balasan...
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",wahai rasulullah bagaimana caranya wahyu turun...
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,permulaaan wahyu yang datang kepada rasulullah...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,berkata ibnu abbas rasulullah shallallahu ala...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,rasulullah shallallahu alaihi wasallam adalah ...

#### Stopwords removal

In [310]:
# !pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords = factory.get_stop_words()
stopwords = factory.create_stop_word_remover()

def stopwords_wrapper(text):
    return stopwords.remove(text)
df_praproses['Praproses'] = df_praproses['Praproses'].apply(stopwords_wrapper)
df_praproses.head()

,Nomor,Kitab,Bab,indo,Matan,Praproses
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",semua perbuatan tergantung niatnya balasan tia...
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",wahai rasulullah bagaimana caranya wahyu turun...
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,permulaaan wahyu datang rasulullah shallallahu...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,berkata ibnu abbas rasulullah shallallahu ala...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,rasulullah shallallahu alaihi wasallam manusia...

#### Tokenization

In [311]:
# !pip install nltk
# import nltk
# nltk.download()

In [312]:
from nltk.tokenize import word_tokenize 

def word_tokenize_wrapper(text):
    return word_tokenize(text)

df_praproses['Token'] = df_praproses['Praproses'].apply(word_tokenize_wrapper)
df_praproses.head()

,Nomor,Kitab,Bab,indo,Matan,Praproses,Token
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",semua perbuatan tergantung niatnya balasan tia...,"[semua, perbuatan, tergantung, niatnya, balasa..."
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",wahai rasulullah bagaimana caranya wahyu turun...,"[wahai, rasulullah, bagaimana, caranya, wahyu,..."
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,permulaaan wahyu datang rasulullah shallallahu...,"[permulaaan, wahyu, datang, rasulullah, shalla..."
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,berkata ibnu abbas rasulullah shallallahu ala...,"[berkata, ibnu, abbas, rasulullah, shallallahu..."
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,rasulullah shallallahu alaihi wasallam manusia...,"[rasulullah, shallallahu, alaihi, wasallam, ma..."

#### POS tagging

In [313]:
# !pip install numpy
# !pip install python-crfsuite

In [314]:
from nltk.tag import CRFTagger
ct = CRFTagger()
ct.set_model_file('all_indo_man_tag_corpus_model.crf.tagger')
df_praproses['POS tag'] = ct.tag_sents(df_praproses['Token'])
df_praproses['POS tag'].loc[0]

[('semua', 'CD'),
 ('perbuatan', 'NN'),
 ('tergantung', 'VB'),
 ('niatnya', 'NN'),
 ('balasan', 'NN'),
 ('tiaptiap', 'CD'),
 ('orang', 'NN'),
 ('tergantung', 'VB'),
 ('apa', 'WH'),
 ('diniatkan', 'VB'),
 ('barangsiapa', 'CD'),
 ('niat', 'NN'),
 ('hijrahnya', 'NN'),
 ('dunia', 'NN'),
 ('ingin', 'RB'),
 ('digapainya', 'RB'),
 ('karena', 'SC'),
 ('seorang', 'NND'),
 ('perempuan', 'NN'),
 ('ingin', 'RB'),
 ('dinikahinya', 'RB'),
 ('hijrahnya', 'RB'),
 ('kepada', 'IN'),
 ('apa', 'WH'),
 ('diniatkan', 'VB')]

In [315]:
df_praproses['POS tag'].loc[df_praproses['Praproses'].str.len().idxmin()]

[('kanan', 'NN'), ('kanan', 'NN')]

## Conceptualization

#### TF-IDF

In [316]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=250)
tfidf = vectorizer.fit_transform(df_praproses['Praproses'])

df_ontologi = pd.DataFrame(vectorizer.get_feature_names_out(), columns=['konsep'])

print(df_ontologi['konsep'])
print("TF-IDF Matrix: ")
print(tfidf.toarray())

0         abbas
1      abdullah
2           abu
3           ada
4        adalah
         ...
245       waktu
246      wanita
247    wasallam
248      yahudi
249        yang
Name: konsep, Length: 250, dtype: object
TF-IDF Matrix:
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.13083873 0.         0.24222858]
 [0.         0.         0.         ... 0.12616547 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.20133463 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.27662938 0.         0.        ]]

#### Word embedding

In [317]:
# !pip install gensim

In [318]:
from gensim.models import Word2Vec

skipgram_model = Word2Vec(sentences=df_praproses['Token'],
                          vector_size=200,  # Dimensionality of the word vectors
                          window=5,         # Maximum distance between the current and predicted word within a sentence
                          sg=1,             # Skip-Gram model (1 for Skip-Gram, 0 for CBOW)
                          min_count=20,      # Ignores all words with a total frequency lower than this
                          workers=4)       # Number of CPU cores to use for training the model
 
# Training
skipgram_model.train(df_praproses['Token'], total_examples=1, epochs=10)
skipgram_model.save("skipgram_model.model")

In [319]:
def word_embedding(text):
    loaded_model = Word2Vec.load("skipgram_model.model")
    return(loaded_model.wv[text])

df_ontologi['relasi'] = df_ontologi['konsep'].apply(word_embedding)
df_ontologi

       konsep                                             relasi
0       abbas  [0.16950825, 0.09708175, 0.018076029, 0.004720...
1    abdullah  [0.17092429, -0.0015457405, 0.008521715, 0.124...
2         abu  [0.010417956, -0.071561456, -0.3007689, -0.273...
3         ada  [0.12111027, -0.18872985, 0.13376524, 0.173211...
4      adalah  [0.09430369, -0.095910355, -0.17170455, 0.2229...
..        ...                                                ...
245     waktu  [0.0075943726, 0.039811827, -0.20645243, 0.104...
246    wanita  [-0.21510231, -0.06178304, 0.0045913938, 0.305...
247  wasallam  [-0.027549233, -0.117887154, -0.26418197, 0.11...
248    yahudi  [-0.05211211, -0.28694648, -0.05102386, 0.2102...
249      yang  [0.0025694356, -0.17334987, -0.0812633, 0.1861...

[250 rows x 2 columns]

#### Agglomerative hierarchical clustering

In [339]:
from sklearn.cluster import AgglomerativeClustering
import numpy as np

X = np.array(df_ontologi['relasi'].to_list())

clustering = AgglomerativeClustering(n_clusters=None,
                                     metric='euclidean',
                                     linkage='average',
                                     distance_threshold=2.5
                                     ).fit(X)

print(clustering.labels_)
df_ontologi['cluster'] = clustering.labels_
df_ontologi.head()

[15  8  1 46 11 39 31 11  2  8  9  2 11  2  2  2 15 15  0  0  2 11  5 37
  4  2 34 10 10 11  1 40 11 47  0 44  0  2  0  0 38 11  0  2 11  2  0 34
  2  6  2  2 19  0 16  2 10  2 14  2  0  2 11 10 11 10 19  0  2 19  2  2
 36  2 25  2  2 20 33  0  1  2 50  2  0  2 11 17 11  7  7  2  2  4 49  2
 12  7  0 45 28  2 43  2 11  3 27  0  0  2  2  2  2  0 11 17 21  0  2 11
 19 24  2  0 17 24 18 18  2 11 19  0 16  5  2  5 36 44  0  4 33 42  2  0
  2  2  6 10  0 30 14  6 10  2  2 32  2  2 11 34  0  0  7  2 40  2  9  2
 16  2  0  0 11  2 10 11  0 24  0  0  2 19 41 19  0  4  4 15 26  9  0  0
  0  0 20 48 19  2 35  2  2  2  0  0 23  0 19  2 22  2 11 19  5  9  2 13
 29  2  5  2  4 16  2 19  2 10  3  3 10  0 11  0  0  0  2 11  5 12 19  4
 15 33  0 32  2  0 21  9  0  0]

     konsep                                             relasi  cluster
0     abbas  [0.16950825, 0.09708175, 0.018076029, 0.004720...       15
1  abdullah  [0.17092429, -0.0015457405, 0.008521715, 0.124...        8
2       abu  [0.010417956, -0.071561456, -0.3007689, -0.273...        1
3       ada  [0.12111027, -0.18872985, 0.13376524, 0.173211...       46
4    adalah  [0.09430369, -0.095910355, -0.17170455, 0.2229...       11

In [340]:
ontologi = df_ontologi.groupby('cluster')
ontologi.apply(display)

            konsep                                             relasi  cluster
18          anshar  [-0.16643749, -0.3082173, -0.04940145, 0.35812...        0
19          antara  [0.0677974, -0.024313355, -0.002390087, 0.1633...        0
34        beberapa  [0.018059557, 0.08783302, 0.00012818327, 0.172...        0
36          beliau  [-0.015630635, 0.06949362, -0.1740668, 0.08329...        0
38          berada  [0.051470593, 0.08606796, 0.13411267, 0.376041...        0
39       berangkat  [-0.062474944, 0.04613006, -0.00489896, 0.1075...        0
42        berjalan  [-0.034480933, 0.27422705, 0.03415013, 0.18032...        0
46         bersama  [0.024188185, 0.11954796, -0.010697863, 0.0232...        0
53          daging  [-0.051705536, -0.2230072, -0.20257612, 0.1428...        0
60              di  [0.018770443, -0.08309807, -0.2052429, 0.13451...        0
67           duduk  [0.10611175, 0.068904094, 0.04491413, 0.298934...        0
79          hingga  [0.03309763, -0.037966445, -0.063086726, 0.185...        0
84            ikut  [-0.07208397, 0.1386919, 0.03250669, 0.1092562...        0
98         kambing  [0.02131129, -0.15520187, -0.11274276, 0.26243...        0
107         keluar  [0.05050921, 0.22361858, 0.0160671, 0.17361158...        0
108       kemudian  [0.08149017, -0.08138878, -0.12839171, 0.32483...        0
113         ketika  [-0.044089418, 0.09472097, -0.008317837, 0.154...        0
117           lalu  [0.121663414, -0.02712382, -0.15143906, 0.2254...        0
123          makan  [-0.10877742, -0.22943416, -0.28053322, 0.2602...        0
131         masjid  [0.0040743626, 0.03770942, 0.01968285, 0.34370...        0
138        melihat  [0.1345351, 0.14646126, -0.03643377, 0.1984755...        0
143  memerintahkan  [-0.07688209, -0.09766635, 0.10385343, 0.14588...        0
148     mendatangi  [-0.1427895, -0.070537396, -0.07340664, 0.2238...        0
160         menuju  [-0.00079568545, 0.06581212, -0.0045812214, 0....        0
161         mereka  [-0.049583927, -0.15068273, -0.08007664, 0.376...        0
170          orang  [-0.13344707, -0.12312549, -0.09338015, 0.1011...        0
171     orangorang  [-0.16790047, -0.12723963, -0.11134693, 0.1245...        0
176           para  [0.041655026, -0.015175416, 0.033033453, 0.170...        0
178         perang  [-0.12801984, 0.084861144, 0.013900455, 0.0285...        0
179          pergi  [-0.08361162, 0.06272836, -0.033574693, 0.1129...        0
184            pun  [0.06488818, 0.076818235, 0.017085634, 0.19716...        0
190          rumah  [0.20591584, 0.272171, 0.024184996, 0.17371859...        0
191           saat  [0.09202015, 0.15572928, -0.019903606, 0.20294...        0
192        sahabat  [0.047997057, 0.08438913, 0.13233064, 0.258539...        0
193          sakit  [-0.015902122, 0.038407005, -0.0341479, 0.1851...        0
202       sebagian  [0.05290292, -0.16752085, 0.0071115503, 0.2766...        0
203         sebuah  [0.021382889, 0.020308178, 0.062205855, 0.3121...        0
205         selalu  [-0.060951654, -0.12279052, -0.08383898, 0.123...        0
229         tempat  [-0.05755902, -0.13705337, -0.00020847455, 0.3...        0
231       tersebut  [0.00902307, -0.2545613, -0.012253841, 0.10913...        0
232           tiba  [0.0668849, -0.03905831, -0.11847013, 0.103777...        0
233       tibatiba  [0.0065997527, 0.06248235, -0.015712393, 0.250...        0
242          untuk  [-0.07657597, -0.07457694, -0.010929469, 0.131...        0
245          waktu  [0.0075943726, 0.039811827, -0.20645243, 0.104...        0
248         yahudi  [-0.05211211, -0.28694648, -0.05102386, 0.2102...        0
249           yang  [0.0025694356, -0.17334987, -0.0812633, 0.1861...        0

      konsep                                             relasi  cluster
2        abu  [0.010417956, -0.071561456, -0.3007689, -0.273...        1
30     bakar  [0.22159126, -0.0054426217, -0.15145889, 0.079...        1
80  hurairah  [0.21238618, -0.12032978, -0.25644362, 0.05963...        1

      konsep                                             relasi  cluster
8        aku  [-0.055830214, 0.026108455, 0.14625922, 0.2049...        2
11       ali  [0.1704755, 0.09688902, 0.014690386, -0.008067...        2
13      anak  [0.14660929, 0.058181863, 0.24224639, 0.371173...        2
14      anas  [0.05940547, 0.1635568, 0.019485423, 0.1258804...        2
15      anda  [-0.09770944, -0.18181889, -0.073501684, 0.149...        2
..       ...                                                ...      ...
219  sungguh  [-0.036868732, -0.16332395, -0.21378687, -0.09...        2
222     tahu  [0.02778701, -0.0026218002, -0.032883722, 0.12...        2
224      tak  [0.03139384, -0.06279423, 0.08370712, 0.161702...        2
234    tidak  [-0.0367641, -0.20959781, -0.024556583, 0.0130...        2
244    wahai  [0.06488315, -0.032198157, -0.08176045, 0.3770...        2

[65 rows x 3 columns]

        konsep                                             relasi  cluster
105      kedua  [0.045703344, -0.105453014, -0.0698333, 0.4180...        3
226     tangan  [-0.089134276, -0.41913548, 0.12643145, 0.5181...        3
227  tangannya  [0.029305385, -0.2049902, 0.06497651, 0.518472...        3

      konsep                                             relasi  cluster
24      ayat  [-0.046446934, -0.18431216, -0.08581554, -0.28...        4
93     kabah  [-0.13408145, 0.17059271, 0.13346744, 0.047525...        4
139  membaca  [0.029392898, -0.007031803, -0.12843956, -0.08...        4
185       qs  [-0.06303433, -0.22737803, -0.033274572, 0.011...        4
186    quran  [0.09181035, 0.013913011, -0.09983507, -0.1869...        4
220    surat  [0.07738902, 0.0040514455, -0.036489062, -0.13...        4
239    turun  [-0.053293772, -0.046109483, -0.16972397, -0.0...        4

           konsep                                             relasi  cluster
22           arah  [-0.15087694, -0.13599475, -0.06207851, 0.3699...        5
133      matahari  [-0.07720023, -0.05409176, -0.21525867, 0.0301...        5
135  melaksanakan  [-0.0011136808, 0.060710084, -0.11638753, -0.0...        5
212        shalat  [-0.224683, -0.12409485, -0.25517416, -0.01984...        5
218         sujud  [0.010230117, -0.035201233, 0.011065912, 0.297...        5
236         tidur  [0.073438406, -0.07844073, -0.19455852, 0.2204...        5

           konsep                                             relasi  cluster
49            bin  [0.28263932, 0.09969637, 0.01349667, -0.078966...        6
146  menceritakan  [0.12810151, -0.20071617, -0.07455612, 0.25125...        6
151   mengabarkan  [0.01872359, -0.06940585, -0.027412172, 0.0625...        6

        konsep                                             relasi  cluster
89      jangan  [-0.26869246, -0.60605145, -0.034049068, 0.348...        7
90   janganlah  [-0.40505135, -0.55265325, -0.034190964, 0.341...        7
97      kalian  [-0.03474417, -0.3204922, -0.27936587, 0.38360...        7
162      minum  [-0.09931564, -0.2876078, -0.09941949, 0.36338...        7

     konsep                                             relasi  cluster
1  abdullah  [0.17092429, -0.0015457405, 0.008521715, 0.124...        8
9        al  [0.23000172, -0.062936395, 0.016611144, -0.161...        8

          konsep                                             relasi  cluster
10        alaihi  [-0.11749317, 0.17843677, -0.21787465, 0.02720...        9
166         nabi  [0.040442128, -0.018745959, -0.16270822, -0.00...        9
189   rasulullah  [0.08482731, 0.023240237, -0.21197139, -0.2301...        9
213  shallallahu  [-0.20898089, 0.27040875, -0.08886775, 0.29928...        9
247     wasallam  [-0.027549233, -0.117887154, -0.26418197, 0.11...        9

          konsep                                             relasi  cluster
27        bagian  [0.13347533, -0.2223672, -0.103193864, 0.29737...       10
28       baginya  [-0.001982847, -0.099395566, 0.008575676, 0.26...       10
56         dapat  [0.09490647, -0.20391285, -0.059265494, 0.1841...       10
63        diberi  [0.021898707, -0.22519775, -0.1689666, -0.0088...       10
65          dosa  [-0.106202915, -0.29280123, 0.07938359, 0.1708...       10
147  mendapatkan  [-0.050544668, -0.24602512, 0.02278753, 0.1166...       10
152    mengambil  [0.13531786, -0.03070043, -0.038654473, 0.2744...       10
174       pahala  [-0.13202617, -0.34786898, 0.030044764, 0.3521...       10
225        tanah  [0.14858249, -0.07166293, -0.017031474, 0.2074...       10
228        telah  [-0.17271167, -0.32631645, 0.14830321, 0.29100...       10

           konsep                                             relasi  cluster
4          adalah  [0.09430369, -0.095910355, -0.17170455, 0.2229...       11
7            akan  [0.02379194, -0.094462544, -0.08589929, -0.001...       11
12          allah  [-0.2543591, -0.24698965, 0.037662774, 0.09349...       11
21        apabila  [-0.23945998, -0.22978914, -0.1577506, 0.20434...       11
29           baik  [-0.17739652, -0.0474314, -0.101519704, 0.1476...       11
32         banyak  [0.2123477, 0.028883291, -0.08486473, 0.160673...       11
41        beriman  [-0.20984551, -0.339951, -0.01571202, 0.250903...       11
44       berpuasa  [-0.08215027, -0.29646498, -0.18139789, 0.0330...       11
62       diantara  [0.120867044, -0.2180767, -0.11782444, 0.06090...       11
64           diri  [-0.12135719, -0.25976938, -0.023800632, 0.112...       11
86          islam  [-0.0693459, 0.10190798, -0.022017218, 0.15580...       11
88          jalan  [-0.09092371, -0.08318801, -0.01970124, 0.1421...       11
104      kebaikan  [-0.048135847, -0.21669814, 0.066150114, 0.134...       11
114        kiamat  [0.08141245, -0.09156809, -0.20520717, 0.16499...       11
119         lebih  [-0.043158837, -0.10070483, -0.08123212, 0.109...       11
129       manusia  [-0.0053223483, -0.10952233, -0.13788584, 0.18...       11
158       menjadi  [-0.09118217, -0.21525751, -0.10625024, 0.1853...       11
172          pada  [0.01803186, -0.059777327, -0.08332503, -0.057...       11
175        paling  [0.19411215, -0.012422247, -0.29936513, 0.3238...       11
210  sesungguhnya  [0.104978114, -0.29598996, -0.19565816, 0.1924...       11
230       terjadi  [-0.086566865, 0.039440326, -0.021558382, 0.00...       11
235      tidaklah  [-0.17258313, -0.2176418, 0.14571522, 0.064560...       11

    konsep                                             relasi  cluster
96    kali  [-0.16447109, 0.13000219, 0.12849386, 0.300764...       12
237   tiga  [-0.10709224, 0.041633792, 0.0362281, 0.364010...       12

    konsep                                             relasi  cluster
215  siapa  [0.037061863, -0.14047112, -0.023185229, 0.411...       13

      konsep                                             relasi  cluster
58    datang  [-0.047825623, 0.07796138, -0.02993752, 0.2465...       14
150  menemui  [-0.0366437, 0.26781747, -0.041607454, 0.13023...       14

          konsep                                             relasi  cluster
0          abbas  [0.16950825, 0.09708175, 0.018076029, 0.004720...       15
16          anhu  [0.18925421, 0.13181539, -0.0471399, -0.161316...       15
17        anhuma  [0.17238234, 0.15799518, 0.05114671, -0.149326...       15
187  radliallahu  [0.22130157, 0.23957096, -0.057143416, -0.1825...       15
240         umar  [-0.008050767, 0.26893672, -0.0027919651, -0.0...       15

     konsep                                             relasi  cluster
54    dalam  [-0.040043578, -0.066939466, 0.09636706, 0.474...       16
132   masuk  [-0.17517973, 0.055838212, 0.07872848, 0.42288...       16
168  neraka  [0.030331492, 0.12591293, 0.16913883, 0.525276...       16
221   surga  [-0.0332948, 0.20460115, 0.22482103, 0.4274791...       16

      konsep                                             relasi  cluster
87       itu  [0.15145393, 0.05694578, 0.13612261, -0.034353...       17
115    kurma  [0.10794499, -0.27991238, -0.07635926, 0.12254...       17
124  makanan  [0.021131268, -0.24433866, -0.03176052, 0.2335...       17

       konsep                                             relasi  cluster
126  malaikat  [-0.01725614, 0.022998266, -0.12034679, 0.1813...       18
127     malam  [0.16583675, 0.16755188, -0.30606854, -0.13928...       18

      konsep                                             relasi  cluster
52     bulan  [0.13847324, 0.061722588, -0.24001528, 0.02968...       19
66       dua  [0.05949114, -0.05456075, -0.0042263814, 0.056...       19
69     empat  [0.10288285, 0.07895034, -0.04107173, 0.077008...       19
120     lima  [0.12674442, -0.070202306, 0.027712721, 0.0976...       19
130     masa  [0.04681228, 0.029549804, -0.03461618, -0.0287...       19
181  pertama  [0.10741369, 0.109122336, -0.02595781, 0.11640...       19
183    puluh  [0.14529611, -0.0061688465, 0.023191571, 0.068...       19
196     sama  [0.0073966915, -0.24210605, -0.023683693, 0.12...       19
206   selama  [0.03771185, -0.15687966, -0.04598991, 0.00032...       19
211   setiap  [0.07347707, -0.12997293, -0.04423493, 0.22081...       19
223    tahun  [-0.08383924, 0.060140125, 0.00926019, -0.1576...       19
238    tujuh  [0.01671743, -0.041266408, -0.012750112, 0.034...       19

        konsep                                             relasi  cluster
77   hendaklah  [-0.09763156, -0.29603457, -0.28056127, 0.3424...       20
194      salah  [-0.049631476, -0.302078, -0.23957162, 0.37730...       20

       konsep                                             relasi  cluster
116  lakilaki  [0.03448271, -0.016933631, -0.040929403, 0.233...       21
246    wanita  [-0.21510231, -0.06178304, 0.0045913938, 0.305...       21

      konsep                                             relasi  cluster
208  seorang  [-0.02126747, -0.14797695, 0.00728373, 0.26089...       22

     konsep                                             relasi  cluster
204  sedang  [-0.13094105, 0.04969954, 0.12535305, 0.306978...       23

       konsep                                             relasi  cluster
121   madinah  [-0.04170483, 0.2608891, 0.07949582, 0.1554222...       24
125    makkah  [-0.07305916, 0.14990844, 0.11880514, 0.028303...       24
177  penduduk  [0.004473134, 0.40749696, 0.2087127, 0.2107593...       24

   konsep                                             relasi  cluster
74   hari  [0.13060904, -0.19685206, -0.45098594, -0.1152...       25

     konsep                                             relasi  cluster
188  rakaat  [0.051204573, 0.13565403, -0.047848865, -0.025...       26

       konsep                                             relasi  cluster
106  keduanya  [-0.23665862, -0.110858865, 0.30533817, 0.1791...       27

    konsep                                             relasi  cluster
100   kamu  [-0.39198062, -0.33168584, -0.09683016, 0.1250...       28

    konsep                                             relasi  cluster
216  suatu  [-0.105007745, -0.09578166, 0.09872165, 0.0521...       29

        konsep                                             relasi  cluster
149  mendengar  [-0.050737288, -0.11133608, -0.04922412, 0.013...       30

   konsep                                             relasi  cluster
6  aisyah  [-0.10183557, 0.11193159, -0.17049748, 0.26650...       31

          konsep                                             relasi  cluster
155  mengucapkan  [-0.052866522, -0.16664983, -0.110909015, 0.28...       32
243           wa  [0.023028165, -0.044554092, -0.1594256, 0.2747...       32

      konsep                                             relasi  cluster
78     hewan  [-0.0931064, -0.102590814, 0.016073292, 0.1416...       33
140  membawa  [-0.13150775, 0.0055538896, -0.043096352, 0.13...       33
241     unta  [0.10674112, -0.04679239, 0.10430213, 0.302674...       33

        konsep                                             relasi  cluster
26   bagaimana  [0.031685676, 0.029697957, -0.033422142, 0.159...       34
47    bertanya  [0.04152303, 0.10370853, 0.063337214, 0.193554...       34
159   menjawab  [0.16289303, -0.03149919, -0.14003061, 0.08679...       34

    konsep                                             relasi  cluster
198   satu  [-0.12986383, -0.23696655, -0.19573495, -0.014...       35

        konsep                                             relasi  cluster
72        haji  [-0.13356999, -0.029686322, -0.054453164, -0.0...       36
136  melakukan  [-0.11946659, -0.20593318, 0.117523484, 0.0018...       36

   konsep                                             relasi  cluster
23   atas  [-0.03696582, -0.20658305, -0.07897079, 0.4353...       37

     konsep                                             relasi  cluster
40  berdiri  [-0.0029493761, -0.129485, -0.14845327, 0.4987...       38

  konsep                                             relasi  cluster
5    air  [0.18747821, 0.06436594, -0.14809357, 0.245974...       39

    konsep                                             relasi  cluster
31    bani  [0.04863996, -0.16727234, -0.13912395, 0.24297...       40
164   musa  [0.16862549, -0.28485817, -0.0055291317, 0.360...       40

    konsep                                             relasi  cluster
182  pohon  [0.18268736, -0.14007813, 0.0027910802, 0.0729...       41

      konsep                                             relasi  cluster
141  memberi  [-0.116207205, -0.28176117, -0.30596343, 0.370...       42

    konsep                                             relasi  cluster
102   kaum  [-0.2557677, -0.26002473, -0.20820962, 0.07013...       43

       konsep                                             relasi  cluster
35       beli  [-0.13129425, -0.42229533, 0.07679662, 0.02272...       44
137  melarang  [-0.06204397, -0.3160665, -0.0014791177, 0.059...       44

   konsep                                             relasi  cluster
99   kami  [-0.15731882, -0.2139043, 0.09151325, 0.114053...       45

  konsep                                             relasi  cluster
3    ada  [0.12111027, -0.18872985, 0.13376524, 0.173211...       46

         konsep                                             relasi  cluster
33  barangsiapa  [-0.38696963, -0.58818924, -0.22057572, 0.3447...       47

    konsep                                             relasi  cluster
195  salam  [-0.15918404, 0.051873237, -0.275463, 0.322392...       48

   konsep                                             relasi  cluster
94   kain  [0.024962986, -0.3571162, -0.091711625, 0.0561...       49

   konsep                                             relasi  cluster
82   ibnu  [0.42745695, 0.12887843, 0.1381182, -0.0747617...       50

C:\Users\habib\AppData\Local\Temp\ipykernel_18004\2050469065.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ontologi.apply(display)

Empty DataFrame
Columns: []
Index: []

## Serialization

In [341]:
from rdflib.namespace import OWL, RDF, RDFS
from rdflib import Graph, Literal, Namespace, URIRef

# Construct the hadis namespace
Hadis = Namespace("http://www.hadits.id/#")

# Create the graph
g = Graph()

# Bind the OWL and Hadis name spaces
g.bind("owl", OWL)
g.bind("hadis", Hadis)

g.add((URIRef('http://www.semanticweb.org/habib/ontologies/2025/2/shahih_bukhari.owl'), RDF.type, OWL.Ontology ))

# Create the node to add to the Graph
Bukhari = URIRef(Hadis["shahih_bukhari"])

# Add the OWL data to the g
g.add((Bukhari, RDF.type, OWL.Class))
g.add((Bukhari, RDFS.subClassOf, OWL.Thing))
g.add((Bukhari, RDFS.label, Literal("Shahih Bukhari")))
g.add((Bukhari, RDFS.comment, Literal("The ontology of the hadith shahih bukhari")))

for cluster in ontologi:

    if len(cluster[1]['konsep']) == 1:
        print(cluster[1]['konsep'])
        # Konsep = URIRef(Bukhari+str(cluster[0]))
        # g.add((Konsep, RDF.type, OWL.Class))
        # g.add((Konsep, RDFS.subClassOf, Bukhari))
        # g.add((Konsep, RDFS.label, Literal(cluster[1]['konsep'])))

    else:
        Konsep = URIRef(Bukhari+str(cluster[0]))
        g.add((Konsep, RDF.type, OWL.Class))
        g.add((Konsep, RDFS.subClassOf, Bukhari))
        g.add((Konsep, RDFS.label, Literal(cluster[0])))

        for daun in cluster[1]['konsep']:

            Daun = URIRef(Konsep+daun)
            g.add((Daun, RDF.type, OWL.Class))
            g.add((Daun, RDFS.subClassOf, Konsep))
            g.add((Daun, RDFS.label, Literal(daun)))

print(g.serialize('shahih_bukhari.owl', format='pretty-xml'))
# print(g.serialize(format='pretty-xml'))

215    siapa
Name: konsep, dtype: object
208    seorang
Name: konsep, dtype: object
204    sedang
Name: konsep, dtype: object
74    hari
Name: konsep, dtype: object
188    rakaat
Name: konsep, dtype: object
106    keduanya
Name: konsep, dtype: object
100    kamu
Name: konsep, dtype: object
216    suatu
Name: konsep, dtype: object
149    mendengar
Name: konsep, dtype: object
6    aisyah
Name: konsep, dtype: object
198    satu
Name: konsep, dtype: object
23    atas
Name: konsep, dtype: object
40    berdiri
Name: konsep, dtype: object
5    air
Name: konsep, dtype: object
182    pohon
Name: konsep, dtype: object
141    memberi
Name: konsep, dtype: object
102    kaum
Name: konsep, dtype: object
99    kami
Name: konsep, dtype: object
3    ada
Name: konsep, dtype: object
33    barangsiapa
Name: konsep, dtype: object
195    salam
Name: konsep, dtype: object
94    kain
Name: konsep, dtype: object
82    ibnu
Name: konsep, dtype: object
[a rdfg:Graph;rdflib:storage [a rdflib:Store;rdfs:label 'Memory']].