## Data Hadis

In [43]:
import pandas as pd

pd.reset_option("^display")

##### Web scraping

In [44]:
df_scraper = pd.read_csv("scraper.csv")
df_scraper = df_scraper.sort_values("Nomor").reset_index().drop('index', axis=1)
df_scraper

,Nomor,Kitab,Bab,indo
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala..."
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur..."
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...
...,...,...,...,...
6981,7004,Tauhid,Firman Allah Ta\'ala: Dan Allah yang mencipata...,'Aku mendengar Nabi shallallahu 'alaihi wasall...
6982,7005,Tauhid,"Bacaan orang yang fajir dan munafik, serta sua...",'Perumpamaan orang mukmin yang membaca Al Qur'...
6983,7006,Tauhid,"Bacaan orang yang fajir dan munafik, serta sua...",'Beberapa orang bertanya Nabi shallallahu 'ala...
6984,7007,Tauhid,"Bacaan orang yang fajir dan munafik, serta sua...","'Akan muncul beberapa orang dari arah timur, m..."
6985,7008,Tauhid,Firman Allah Ta\'ala: dan kami letakkan neraca...,'Nabi shallallahu 'alaihi wasallam bersabda: '...

In [45]:
df_scraper['indo'] = df_scraper['indo'].str.replace("; \"",": \"")
df_scraper['matan'] = [x.split(": \"",1)[-1] for x in df_scraper.indo]
df_scraper.head()

,Nomor,Kitab,Bab,indo,matan
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala..."
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur..."
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...

#### bukhari.json

In [46]:
df_bukhari = pd.read_json("bukhari.json")
df_bukhari = df_bukhari.sort_values("haditsId").reset_index().drop('index', axis=1)
df_bukhari.head()

,imam,kitabId,babId,haditsId,arab,indo,sanads,related
0,bukhari,1,1,1,حَدَّثَنَا الْحُمَيْدِيُّ عَبْدُ اللَّهِ بْنُ ...,Telah menceritakan kepada kami [Al Humaidi Abd...,"[{'sanad': ['4698', '3443', '8272', '6796', '5...","[{'imam': 'bukhari', 'haditsId': '52'}, {'imam..."
1,bukhari,1,1,2,حَدَّثَنَا عَبْدُ اللَّهِ بْنُ يُوسُفَ قَالَ أ...,Telah menceritakan kepada kami [Abdullah bin Y...,"[{'sanad': ['5175', '6659', '8055', '5594', '4...","[{'imam': 'bukhari', 'haditsId': '2976'}, {'im..."
2,bukhari,1,1,3,حَدَّثَنَا يَحْيَى بْنُ بُكَيْرٍ قَالَ حَدَّثَ...,Telah menceritakan kepada kami [Yahya bin Buka...,"[{'sanad': ['8297', '6641', '5688', '7272', '5...","[{'imam': 'bukhari', 'haditsId': '4572'}, {'im..."
3,bukhari,1,1,4,حَدَّثَنَا مُوسَى بْنُ إِسْمَاعِيلَ قَالَ حَدّ...,Telah menceritakan kepada kami [Musa bin Isma'...,"[{'sanad': ['7721', '8153', '7710', '3307', '4...","[{'imam': 'bukhari', 'haditsId': '6970'}, {'im..."
4,bukhari,1,1,5,حَدَّثَنَا عَبْدَانُ قَالَ أَخْبَرَنَا عَبْدُ ...,Telah menceritakan kepada kami [Abdan] dia ber...,"[{'sanad': ['4943', '4716', '8621', '7272', '5...","[{'imam': 'bukhari', 'haditsId': '1769'}, {'im..."

## Preproccess

In [47]:
# df_praproses = df_bukhari
df_praproses = df_scraper

# df_praproses['matan'] = [x.split(": \"",1)[-1] for x in df_praproses.indo]

df_praproses['clean'] = df_praproses['indo']
# df_praproses['clean'] = df_praproses['matan']

#### Remove punctuation

In [48]:
import string
df_praproses['clean'] = df_praproses['clean'].str.replace('[{}]'.format(string.punctuation), '', regex=True)
# df_praproses['clean'] = df_praproses['matan'].str.replace('[{}]'.format(string.punctuation), '', regex=True)
df_praproses.head()

,Nomor,Kitab,Bab,indo,matan,clean
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",Semua perbuatan tergantung niatnya dan balasan...
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",Wahai Rasulullah bagaimana caranya wahyu turun...
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,Permulaaan wahyu yang datang kepada Rasulullah...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,Berkata Ibnu Abbas Rasulullah shallallahu ala...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu alaihi wasallam adalah ...

#### Stopwords removal

In [49]:
# !pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary
from nltk.corpus import stopwords

factory = StopWordRemoverFactory()
stopwords_factory = factory.get_stop_words()

more_stopwords = stopwords.words('indonesian')
stopwords_factory = ArrayDictionary(stopwords_factory+more_stopwords)
stopwords_factory = StopWordRemover(stopwords_factory)

def stopwords_wrapper(text):
    return stopwords_factory.remove(text)
df_praproses['clean'] = df_praproses['clean'].apply(stopwords_wrapper)
df_praproses.head()

,Nomor,Kitab,Bab,indo,matan,clean
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",Semua perbuatan tergantung niatnya balasan tia...
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",Wahai Rasulullah caranya wahyu turun engkau Ma...
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,Permulaaan wahyu datang Rasulullah shallallahu...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,Berkata Ibnu Abbas Rasulullah shallallahu ala...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu alaihi wasallam manusia...

#### Lemmatizer

In [50]:
from nlp_id.lemmatizer import Lemmatizer 

lemmatizer = Lemmatizer() 

def lemmatize_wrapper(text):
    return lemmatizer.lemmatize(text) 

df_praproses['clean'] = df_praproses['clean'].apply(lemmatize_wrapper)
df_praproses.head()

,Nomor,Kitab,Bab,indo,matan,clean
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",semua buat gantung niat balas tiaptiap orang g...
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",wahai rasulullah cara wahyu turun engkau maka ...
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,permulaaan wahyu datang rasulullah shallallahu...
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,kata ibnu abbas rasulullah shallallahu alaihi ...
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,rasulullah shallallahu alaihi wasallam manusia...

#### Tokenizer

In [51]:
import nltk
import sklearn

print('The nltk version is {}.'.format(nltk.__version__))
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The nltk version is 3.8.1.
The scikit-learn version is 1.2.2.

In [52]:
# from nlp_id.tokenizer import Tokenizer 
# tokenizer = Tokenizer() 

from nlp_id.tokenizer import PhraseTokenizer 
tokenizer = PhraseTokenizer() 

def tokenize_wrapper(text):
    return tokenizer.tokenize(text)

df_praproses['token'] = df_praproses['matan'].apply(tokenize_wrapper)
df_praproses.head()

c:\Users\habib\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DictVectorizer from version 0.22 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\habib\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\habib\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\habib\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator Pipeline from version 0.22 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

,Nomor,Kitab,Bab,indo,matan,clean,token
0,1,Permulaan wahyu,Permulaan wahyu',"'Semua perbuatan tergantung niatnya, dan (bala...","'Semua perbuatan tergantung niatnya, dan (bala...",semua buat gantung niat balas tiaptiap orang g...,"[', Semua, perbuatan, tergantung, niat, nya, ,..."
1,2,Permulaan wahyu,Permulaan wahyu',"'Wahai Rasulullah, bagaimana caranya wahyu tur...","'Wahai Rasulullah, bagaimana caranya wahyu tur...",wahai rasulullah cara wahyu turun engkau maka ...,"[', Wahai Rasulullah, ,, bagaimana, caranya, w..."
2,3,Permulaan wahyu,Permulaan wahyu','Permulaaan wahyu yang datang kepada Rasululla...,'Permulaaan wahyu yang datang kepada Rasululla...,permulaaan wahyu datang rasulullah shallallahu...,"[', Permulaaan, wahyu, yang, datang, kepada, R..."
3,4,Permulaan wahyu,Permulaan wahyu',' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,' Berkata Ibnu 'Abbas: 'Rasulullah shallallahu...,kata ibnu abbas rasulullah shallallahu alaihi ...,"[', Berkata Ibnu, ', Abbas, :, ', Rasulullah, ..."
4,5,Permulaan wahyu,Permulaan wahyu',Rasulullah shallallahu 'alaihi wasallam adalah...,Rasulullah shallallahu 'alaihi wasallam adalah...,rasulullah shallallahu alaihi wasallam manusia...,"[Rasulullah, shallallahu, ', alaihi, wasallam,..."

#### POS tagger

In [53]:
# from nlp_id.postag import PosTag
# postagger = PosTag() 

# def postag_wrapper(text):
#     return postagger.get_pos_tag(text)

# df_praproses['pos tag'] = df_praproses['clean'].apply(postag_wrapper)
# df_praproses['pos tag'].loc[0]

In [54]:
# df_praproses['pos tag'].loc[df_praproses['clean'].str.len().idxmin()]

## Conceptualization

#### TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=250)
tfidf = vectorizer.fit_transform(df_praproses['matan'])

df_ontologi = pd.DataFrame(vectorizer.get_feature_names_out(), columns=['konsep'])

print(df_ontologi['konsep'])
print("TF-IDF Matrix: ")
print(tfidf.toarray())

AttributeError: 'list' object has no attribute 'lower'

#### Word embedding

In [56]:
# !pip install gensim

In [57]:
from gensim.models import Word2Vec

skipgram_model = Word2Vec(sentences=df_praproses['token'],
                          vector_size=200,  # Dimensionality of the word vectors
                          window=5,         # Maximum distance between the current and predicted word within a sentence
                          sg=1,             # Skip-Gram model (1 for Skip-Gram, 0 for CBOW)
                          min_count=20,      # Ignores all words with a total frequency lower than this
                          workers=4)       # Number of CPU cores to use for training the model
 
# Training
skipgram_model.train(df_praproses['token'], total_examples=1, epochs=10)
skipgram_model.save("skipgram_model.model")

In [58]:
def word_embedding(text):
    loaded_model = Word2Vec.load("skipgram_model.model")
    return(loaded_model.wv[text])

df_ontologi['relasi'] = df_ontologi['konsep'].apply(word_embedding)
df_ontologi

KeyError: "Key 'abbas' not present"

#### Agglomerative hierarchical clustering

In [ ]:
from sklearn.cluster import AgglomerativeClustering
import numpy as np

X = np.array(df_ontologi['relasi'].to_list())

clustering = AgglomerativeClustering(n_clusters=None,
                                     metric='euclidean',
                                     linkage='average',
                                     distance_threshold=2.7
                                     ).fit(X)

print(clustering.labels_)
df_ontologi['cluster'] = clustering.labels_
df_ontologi.head()

[ 2 32 17  0  0  6 31  0  0  0 11  0  0  5  0  6  0 28  0  0  0  2 13  0
  0  0  0 14  0 11  2 11  0 14  0  0  0  7  0  2 18 23 29  0  0  0  0 10
  0  2  6  0  0  0  2  5  0  0 27  0  0  9  0  0  0  0 28  0  0  0  3  0
 12 14  0  0  0  5 30  0 25  0  0  0  0  0  0  9 21  0  0 28  9  2  0  3
  5  0  0  0  0  0 19  9  0  9 29  0 20  2  6  0 22  0  0  0 10  0  0 13
  0  0  0  0  6  0  6  0  0  0  0 24  0  0  4 16  0  0 29  0  6  0  0  0
  0  0  0  3  1  0  1 27  4  0  0  0  0  0  0  0  7  0  8  0 27  0  0  0
  0  0  6  0  0 13  0 13  0  0  2  0 24 25  0  0 11 11  2  4 21  0  1  4
  0 13  0  0  9 26  0  0 12  0  0  0  0 21  0  4  0  0  0  0  0  0  0  0
  0  0 11 27  0  6 15  0  0  0  0  0  0  0  0  9 22  0  0 11  6  3 20  0
  0 13  3  0  0  0  0  0  3  0]

     konsep                                             relasi  cluster
0     abbas  [0.11118696, 0.017720541, -0.16366564, -0.0076...        2
1  abdullah  [0.10357967, 0.09956439, -0.15062489, 0.350253...       32
2       abu  [-0.2631076, -0.26030478, -0.1559846, 0.216880...       17
3       ada  [-0.07764775, 0.049738694, 0.00069181505, -0.0...        0
4    adalah  [-0.0965548, -0.020780994, -0.2737816, -0.0087...        0

In [ ]:
ontologi = df_ontologi.groupby('cluster')
ontologi.apply(display)

       konsep                                             relasi  cluster
3         ada  [-0.07764775, 0.049738694, 0.00069181505, -0.0...        0
4      adalah  [-0.0965548, -0.020780994, -0.2737816, -0.0087...        0
7        akan  [-0.2114218, -0.0738184, -0.04356395, 0.192816...        0
8       akhir  [-0.15552601, 0.086908154, -0.13807227, 0.2633...        0
9         aku  [-0.27208036, 0.089702435, -0.043393012, 0.302...        0
..        ...                                                ...      ...
244     wajah  [-0.13645814, 0.035696935, 0.1787925, 0.145962...        0
245     wajib  [0.047855906, 0.05930141, 0.021869583, 0.13639...        0
246    wanita  [0.19860908, 0.028813325, -0.4870168, 0.076974...        0
247  wasallam  [-0.07127026, 0.056569833, -0.19440567, 0.2511...        0
249      yang  [-0.1377028, 0.02612551, -0.06508758, -0.01360...        0

[151 rows x 3 columns]

     konsep                                             relasi  cluster
148   malam  [-0.36637092, 0.32261395, -0.17930949, -0.0610...        1
150  masjid  [-0.24910589, -0.17290124, -0.02179424, 0.0391...        1
190   rumah  [-0.40387332, -0.04242757, -0.2672723, 0.03499...        1

          konsep                                             relasi  cluster
0          abbas  [0.11118696, 0.017720541, -0.16366564, -0.0076...        2
21          anhu  [-0.04017126, -0.211564, 0.05636307, 0.1476792...        2
30            az  [0.036152095, -0.2495645, -0.2485278, 0.257739...        2
39         bapak  [0.07767592, -0.1624595, -0.32582548, 0.280243...        2
49           bin  [0.07012783, -0.20900398, -0.19708718, 0.41688...        2
54        cerita  [0.06867451, -0.123718865, -0.11810138, 0.2720...        2
93          ibnu  [0.018830225, -0.17221653, -0.23667856, 0.2263...        2
109        kabar  [0.25180987, -0.18297812, -0.22679536, 0.23094...        2
178       pernah  [-0.122035906, -0.17945454, -0.09396595, 0.016...        2
186  radliallahu  [-0.3401813, -0.28907767, -0.14160196, 0.16082...        2

       konsep                                             relasi  cluster
70        doa  [-0.06547764, -0.15682699, 0.46458495, 0.07383...        3
95       ilah  [-0.10139617, -0.14007676, 0.29589546, 0.12796...        3
147  malaikat  [-0.32468042, 0.011688895, 0.19613245, 0.08968...        3
237      ucap  [-0.08075013, -0.16165525, 0.09086481, 0.27391...        3
242        wa  [-0.11931632, -0.22026478, 0.42175397, 0.17083...        3
248        ya  [0.052021697, -0.04740667, 0.18494157, 0.38637...        3

       konsep                                             relasi  cluster
134   laksana  [0.038425762, -0.09425974, -0.14585938, 0.1190...        4
152  matahari  [0.01427821, -0.021141633, -0.07428554, 0.1493...        4
187    rakaat  [-0.013478892, -0.060593024, -0.26653174, 0.31...        4
191      saat  [-0.2030301, 0.13645992, -0.053372014, -0.0787...        4
207    shalat  [-0.101248674, -0.02786794, -0.12243444, 0.215...        4

    konsep                                             relasi  cluster
13   allah  [-0.20533453, -0.06710532, 0.2854467, 0.128988...        5
55   cinta  [-0.039036896, 0.042349327, 0.08150499, 0.2455...        5
77  firman  [-0.27527502, -0.11401957, 0.11336469, 0.05125...        5
96    iman  [0.12961894, 0.36739498, -0.11895651, 0.172774...        5

     konsep                                             relasi  cluster
5       air  [-0.014806887, 0.16660191, -0.03952892, 0.1386...        6
15    ambil  [0.11623223, 0.16751856, 0.026239824, 0.287788...        6
50     buah  [-0.009259454, 0.10873817, 0.13860255, -0.0889...        6
110    kain  [0.08038973, -0.09592507, 0.10280867, 0.030458...        6
124    kena  [0.2213879, 0.037446037, 0.011370057, 0.074428...        6
126  kepala  [-0.16920526, -0.087038375, 0.24344876, 0.1090...        6
140   letak  [-0.11979478, -0.029106447, 0.10093759, 0.2002...        6
170   pakai  [0.13861167, -0.104555964, 0.2949012, 0.118046...        6
221   tanah  [-0.101057485, 0.11718799, 0.3487031, 0.050329...        6
236   tutup  [-0.16122726, 0.12010355, -0.0056062974, 0.074...        6

    konsep                                             relasi  cluster
37    bani  [-0.13955076, -0.0037241431, -0.11109708, 0.04...        7
160   musa  [0.018591085, -0.041292336, -0.12604827, 0.296...        7

    konsep                                             relasi  cluster
162   nama  [-0.10858184, -0.04699153, 0.061998535, -0.098...        8

     konsep                                             relasi  cluster
61     dari  [-0.059587214, 0.20409098, -0.28199592, 0.3060...        9
87   hendak  [-0.12532446, 0.19334027, 0.0817168, 0.2038525...        9
92       ia  [0.017089728, 0.16689716, -0.17791153, 0.22230...        9
103  jangan  [-0.23213299, 0.011931952, -0.014978885, 0.040...        9
105    jika  [0.0898772, 0.076783605, -0.0758398, 0.2463414...        9
196   salah  [-0.061595418, 0.23417334, -0.12954152, 0.1979...        9
231   tidur  [-0.3157317, 0.30954546, -0.051865265, 0.03529...        9

    konsep                                             relasi  cluster
47    beri  [0.26083183, -0.058201894, 0.03305537, 0.27491...       10
116   kamu  [0.13993339, 0.24625684, -0.3663503, 0.2639306...       10

    konsep                                             relasi  cluster
10      al  [-0.13447015, -0.0026838575, -0.11208619, 0.09...       11
29    ayat  [-0.19984512, -0.08224452, 0.15725379, -0.1878...       11
31    baca  [-0.26479426, -0.097385556, 0.30040634, 0.1435...       11
184     qs  [-0.3362071, -0.12237322, 0.19647798, 0.019233...       11
185  quran  [-0.15561646, 0.03384784, 0.18551137, 0.041815...       11
218  surat  [-0.21498781, -0.0062230485, 0.06734268, 0.075...       11
235  turun  [-0.24731962, -0.10434022, 0.22709416, -0.2551...       11

    konsep                                             relasi  cluster
72     dua  [-0.14579624, 0.04673382, -0.05784015, 0.14316...       12
200   satu  [0.17348683, 0.18325432, -0.17365624, 0.076906...       12

      konsep                                             relasi  cluster
22    anshar  [0.052436657, -0.10607299, -0.15327063, 0.1357...       13
119     kaum  [-0.12627947, -0.051764727, 0.03283832, 0.0761...       13
173     para  [0.037396777, -0.027479189, -0.10346105, 0.145...       13
175   perang  [0.0008825313, 0.009802579, 0.2944916, 0.06711...       13
193  sahabat  [0.3594683, 0.047863565, 0.077625535, 0.060907...       13
241     utus  [-0.0946457, -0.1017413, 0.019788045, 0.133784...       13

   konsep                                             relasi  cluster
27   atas  [-0.38805947, -0.23468684, 0.09788336, 0.12583...       14
33   bagi  [0.102912165, 0.04623085, -0.11611823, 0.30706...       14
73  duduk  [-0.1257547, -0.15764628, -0.18998414, 0.00166...       14

     konsep                                             relasi  cluster
222  tangan  [-0.22592728, -0.056079023, 0.17348693, 0.3660...       15

    konsep                                             relasi  cluster
135   laku  [0.14838438, 0.106740505, -0.114143014, 0.2135...       16

  konsep                                             relasi  cluster
2    abu  [-0.2631076, -0.26030478, -0.1559846, 0.216880...       17

         konsep                                             relasi  cluster
40  barangsiapa  [-0.029475445, 0.13119343, -0.061734006, 0.025...       18

    konsep                                             relasi  cluster
102  jalan  [-0.03152223, 0.32940567, -0.0046031293, 0.197...       19

    konsep                                             relasi  cluster
108  kabah  [-0.22589034, -0.2293241, -0.008580784, -0.064...       20
238   umar  [0.002328734, -0.020429036, -0.2972955, 0.1049...       20

       konsep                                             relasi  cluster
88      hewan  [0.12856503, -0.07474789, 0.073133186, -0.1499...       21
188    rambut  [0.19863342, -0.096631736, 0.06860125, 0.06655...       21
205  sembelih  [0.15630959, -0.06153501, 0.07921341, -0.08205...       21

    konsep                                             relasi  cluster
112   kali  [-0.061740555, 0.1286852, 0.01066313, 0.442955...       22
232   tiga  [-0.14383501, 0.14890786, 0.022115279, 0.13258...       22

   konsep                                             relasi  cluster
41   bawa  [-0.18665373, 0.13493341, 0.15940933, -0.18628...       23

    konsep                                             relasi  cluster
131  kurma  [0.119788036, 0.042205885, 0.1516195, -0.11257...       24
180  pohon  [0.010927046, -0.0018245274, 0.19485897, -0.25...       24

    konsep                                             relasi  cluster
80    haji  [0.11247484, -0.0641864, -0.2136847, -0.148664...       25
181  puasa  [0.29239145, 0.25180003, -0.13221353, -0.02062...       25

    konsep                                             relasi  cluster
197  salam  [0.0691545, 0.08382156, -0.26070964, 0.340884,...       26

     konsep                                             relasi  cluster
58    dalam  [-0.27935496, -0.07195888, 0.079808794, 0.0056...       27
151   masuk  [-0.2640699, -0.0158205, 0.07216593, 0.2046392...       27
164  neraka  [-0.38285738, -0.12293429, 0.046836637, 0.1151...       27
219   surga  [-0.35753068, -0.07656499, -0.13810393, 0.1488...       27

      konsep                                             relasi  cluster
17      anas  [0.15857847, -0.12743378, -0.12025588, 0.34026...       28
66    dengar  [0.09443955, -0.079855405, 0.08811238, 0.27954...       28
91  hurairah  [-0.33778334, -0.09763533, 0.22142185, 0.31034...       28

     konsep                                             relasi  cluster
42     beli  [0.4402826, -0.09602836, 0.22206068, 0.0545268...       29
106    jual  [0.47079977, -0.06177695, 0.24447733, 0.039299...       29
138  larang  [0.2913935, -0.14951548, -0.03751054, 0.079573...       29

   konsep                                             relasi  cluster
78  hadap  [-0.20123851, -0.10561516, 0.098732024, -0.315...       30

   konsep                                             relasi  cluster
6  aisyah  [0.15280199, -0.21148582, -0.2117791, 0.067549...       31

     konsep                                             relasi  cluster
1  abdullah  [0.10357967, 0.09956439, -0.15062489, 0.350253...       32

C:\Users\habib\AppData\Local\Temp\ipykernel_14508\2050469065.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ontologi.apply(display)

Empty DataFrame
Columns: []
Index: []

## Serialization

In [ ]:
from rdflib.namespace import OWL, RDF, RDFS
from rdflib import Graph, Literal, Namespace, URIRef

# Construct the hadis namespace
Hadis = Namespace("http://www.hadits.id/#")

# Create the graph
g = Graph()

# Bind the OWL and Hadis name spaces
g.bind("owl", OWL)
g.bind("hadis", Hadis)

g.add((URIRef('http://www.semanticweb.org/habib/ontologies/2025/2/shahih_bukhari.owl'), RDF.type, OWL.Ontology ))

# Create the node to add to the Graph
Bukhari = URIRef(Hadis["shahih_bukhari"])

# Add the OWL data to the g
g.add((Bukhari, RDF.type, OWL.Class))
g.add((Bukhari, RDFS.subClassOf, OWL.Thing))
g.add((Bukhari, RDFS.label, Literal("Shahih Bukhari")))
g.add((Bukhari, RDFS.comment, Literal("The ontology of the hadith shahih bukhari")))

for cluster in ontologi:

    if len(cluster[1]['konsep']) == 1:
        print(cluster[1]['konsep'])
        # Konsep = URIRef(Bukhari+str(cluster[0]))
        # g.add((Konsep, RDF.type, OWL.Class))
        # g.add((Konsep, RDFS.subClassOf, Bukhari))
        # g.add((Konsep, RDFS.label, Literal(cluster[1]['konsep'])))

    else:
        Konsep = URIRef(Bukhari+str(cluster[0]))
        g.add((Konsep, RDF.type, OWL.Class))
        g.add((Konsep, RDFS.subClassOf, Bukhari))
        g.add((Konsep, RDFS.label, Literal(cluster[0])))

        for daun in cluster[1]['konsep']:

            Daun = URIRef(Konsep+daun)
            g.add((Daun, RDF.type, OWL.Class))
            g.add((Daun, RDFS.subClassOf, Konsep))
            g.add((Daun, RDFS.label, Literal(daun)))

print(g.serialize('shahih_bukhari.owl', format='pretty-xml'))
# print(g.serialize(format='pretty-xml'))

162    nama
Name: konsep, dtype: object
222    tangan
Name: konsep, dtype: object
135    laku
Name: konsep, dtype: object
2    abu
Name: konsep, dtype: object
40    barangsiapa
Name: konsep, dtype: object
102    jalan
Name: konsep, dtype: object
41    bawa
Name: konsep, dtype: object
197    salam
Name: konsep, dtype: object
78    hadap
Name: konsep, dtype: object
6    aisyah
Name: konsep, dtype: object
1    abdullah
Name: konsep, dtype: object
[a rdfg:Graph;rdflib:storage [a rdflib:Store;rdfs:label 'Memory']].